In [1]:
import pandas as pd
import numpy as np


arrivals = pd.read_csv("./llegada_mensual_pasajeros_aeropuerto_de_origen_internacional.csv", sep = ';')
departures = pd.read_csv("./salida_mensual_pasajeros_aeropuerto_destino_internacional.csv", sep = ';')

arrivals.head()

   lle_periodo lle_origenpax lle_cod        lle_indicador lle_valor
0       202202   El Salvador      SV  LLEGADA_PAX_INTERNA       2.0
1       202202          Cuba      CU  LLEGADA_PAX_INTERNA       2.0
2       202202        México      MX  LLEGADA_PAX_INTERNA   10576.0
3       202202  Islas Caimán      KY  LLEGADA_PAX_INTERNA       1.0
4       202202         Chile      CL  LLEGADA_PAX_INTERNA    1253.0

In [2]:
arrivals['lle_periodo'] = pd.to_datetime(arrivals['lle_periodo'], format='%Y%m')
arrivals.set_index('lle_periodo', inplace=True)
arrivals.head()

            lle_origenpax lle_cod        lle_indicador lle_valor
lle_periodo
2022-02-01    El Salvador      SV  LLEGADA_PAX_INTERNA       2.0
2022-02-01           Cuba      CU  LLEGADA_PAX_INTERNA       2.0
2022-02-01         México      MX  LLEGADA_PAX_INTERNA   10576.0
2022-02-01   Islas Caimán      KY  LLEGADA_PAX_INTERNA       1.0
2022-02-01          Chile      CL  LLEGADA_PAX_INTERNA    1253.0

In [3]:
arrivals.sort_index(inplace=True)
arrivals.head()

            lle_origenpax lle_cod        lle_indicador lle_valor
lle_periodo
2007-01-01       Colombia      CO  LLEGADA_PAX_INTERNA     164.0
2007-01-01         Canadá      CA  LLEGADA_PAX_INTERNA       7.0
2007-01-01      Venezuela      VE  LLEGADA_PAX_INTERNA    2797.0
2007-01-01        Uruguay      UY  LLEGADA_PAX_INTERNA      18.0
2007-01-01        Turquía      TR  LLEGADA_PAX_INTERNA       0.0